version: "3.8"

services:
  stream:
    build: .
    restart: always
    shm_size: "2gb"
    environment:
      - STREAM_URL=${STREAM_URL:-https://hodlwarz.com}
      - STREAM_KEY=${STREAM_KEY}
      - RTMP_SERVER=${RTMP_SERVER:-rtmps://pump-prod-tg2x8veh.rtmp.livekit.cloud/x}
      - RESOLUTION=${RESOLUTION:-1920x1080}
      - FPS=${FPS:-30}
      - BITRATE=${BITRATE:-3000k}
    env_file:
      - .env
